```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# Conclusions

While some of the earliest forms of cancer trearment in the 20th century focused on targeting fast growing cells, somatic variant interpretaions in cancer increasingly play an important role in the clinic, as targeting of specific variants has become a central part of patient treatment. This course has been designed to give an introductory overview of this growing field. Having worked through the course material, readers should gain familiarity with the reference genome, and the basics of next generation sequencing and allignment to the reference. The basic somatic variant types should be familiar, as well as basic evidence types associated to somatic variants in the clinical context. Guidelines covering somatic variant interpretation should be familiar to the reader. An overview of ClinGen and somatic variant interpretatino knowledgebases has been provided, along with an overview of the CIViC knowledgebase. With this, students should be well versed in the basics of how somatic cancer varaints are currently thought about and the impact they have on patinet care in the clinic.  

